sudo: required

language: python

services:
  - docker

python:
    - "3.5"

before_install:
  - sudo apt-get update
  - sudo apt-get install sshpass

install: "pip install -r requirements.txt"

script: 
  - python --version

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t shaobol/odes:$TRAVIS_BRANCH-$TRAVIS_BUILD_ID --build-arg POSTGRES_ADDR=$POSTGRES_ADDR --build-arg POSTGRES_PASSWORD=$POSTGRES_PASSWORD --build-arg POSTGRES_USER=$POSTGRES_USER . 
  - docker push shaobol/odes:$TRAVIS_BRANCH-$TRAVIS_BUILD_ID;
  - sshpass -p $VPS_PASSWORD ssh -o stricthostkeychecking=no root@$VPS_HOST "sudo /home/saukymo/odes/deploy.sh $TRAVIS_BRANCH-$TRAVIS_BUILD_ID"